### ISSUE TITLE
telethon problem 

### ISSUE THREAD

**Issue by Jax15161** [vanhbakaa/Notpixel-paid-version#2]
when I run a script using telethon having problems you say telethon support

**Comment by Jax15161** [comment]
when I run a script using telethon having problems you say telethon support
![IMG_20241027_130510](https://github.com/user-attachments/assets/d2bcf9e4-c34e-4cc0-bdae-63c3283ae9c7)

**Comment by vanhbakaa** [comment]
> when I run a script using telethon having problems you say telethon support ![IMG_20241027_130510](https://private-user-images.githubusercontent.com/119857795/380471575-d2bcf9e4-c34e-4cc0-bdae-63c3283ae9c7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwMTE4MjAsIm5iZiI6MTczMDAxMTUyMCwicGF0aCI6Ii8xMTk4NTc3OTUvMzgwNDcxNTc1LWQyYmNmOWU0LWMzNGUtNGNjMC1iZGFlLTYzYzMyODNhZTljNy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyN1QwNjQ1MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZjJiM2M1MmE4MTYwMWVjMTRiNTY0ZjhiYWFkYjlmZjBjMDRhYjllMDNlZmJmYjRkMGZlOWMwYzBmZTBkY2EyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.V-PLQaiZGEGwdqAhRZJMDJ1Eb2Y-aOEJiPtQPF8-ceM)

it's not support telethon yet
